#!/bin/bash
# Generate docker-compose.ha.yml from IMPLEMENTATION_GUIDELINES §3 Component Inventory
# Usage: ./scripts/generate-ha-compose.sh [port_base]
# This is the execution-level deploy agent capability — dynamic service discovery

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
GUIDELINES="$REPO_ROOT/docs/IMPLEMENTATION_GUIDELINES.md"
OUTPUT="$REPO_ROOT/docker-compose.ha.generated.yml"
PORT_BASE=${1:-30000}
INCREMENT=5

if [ ! -f "$GUIDELINES" ]; then
    echo "⛔ docs/IMPLEMENTATION_GUIDELINES.md not found"
    exit 1
fi

echo "╔══════════════════════════════════════╗"
echo "║  HA Compose Generator                ║"
echo "║  Port base: $PORT_BASE (+$INCREMENT)           ║"
echo "╚══════════════════════════════════════╝"

# Extract services from IMPLEMENTATION_GUIDELINES
# Look for the services table in Local Dev Environment section
echo ""
echo "Discovering services from IMPLEMENTATION_GUIDELINES..."

# Parse service table (| Service | Port | Image | Purpose |)
SERVICES=$(python3 << PYEOF
import re, sys

with open("$GUIDELINES") as f:
    content = f.read()

# Find the services table
in_table = False
services = []
for line in content.split('\n'):
    if '| Service' in line and 'Port' in line:
        in_table = True
        continue
    if in_table and line.startswith('|---'):
        continue
    if in_table and line.startswith('|'):
        parts = [p.strip() for p in line.split('|')[1:-1]]
        if len(parts) >= 3:
            name = parts[0].lower().strip()
            port = parts[1].strip()
            image = parts[2].strip() if len(parts) > 2 else ''
            purpose = parts[3].strip() if len(parts) > 3 else ''
            # Classify
            if 'postgres' in name or 'mysql' in name or 'mongo' in name or 'redis' in name:
                stype = 'stateful'
            elif 'jaeger' in name or 'prometheus' in name or 'otel' in name or 'grafana' in name:
                stype = 'shared'
            elif 'localstack' in name:
                stype = 'infrastructure'
            else:
                stype = 'stateless'
            services.append(f"{name}|{port}|{image}|{stype}|{purpose}")
    elif in_table and not line.startswith('|'):
        in_table = False

for s in services:
    print(s)
PYEOF
)

if [ -z "$SERVICES" ]; then
    echo "⛔ No services found in IMPLEMENTATION_GUIDELINES"
    exit 1
fi

# Display discovered services
echo ""
echo "Services discovered:"
PORT_IDX=0
echo "$SERVICES" | while IFS='|' read -r name port image stype purpose; do
    EAST_PORT=$((PORT_BASE + PORT_IDX))
    echo "  $name ($stype) → east:$EAST_PORT"
    PORT_IDX=$((PORT_IDX + INCREMENT))
done

echo ""
echo "Generating $OUTPUT..."

# Generate the compose file
python3 << PYEOF > "$OUTPUT"
import sys

port_base = $PORT_BASE
increment = $INCREMENT
services_raw = """$SERVICES"""

services = []
for line in services_raw.strip().split('\n'):
    parts = line.split('|')
    if len(parts) >= 4:
        services.append({
            'name': parts[0],
            'port': parts[1],
            'image': parts[2],
            'type': parts[3],
            'purpose': parts[4] if len(parts) > 4 else ''
        })

print("# AUTO-GENERATED from IMPLEMENTATION_GUIDELINES §3")
print(f"# Port allocation: base={port_base}, increment={increment}")
print(f"# Generated by scripts/generate-ha-compose.sh")
print("")
print("services:")

port_idx = 0
west_port_idx = len([s for s in services if s['type'] == 'stateless']) * increment + \
                len([s for s in services if s['type'] == 'stateful']) * increment

# Primary region port overrides
for s in services:
    east_port = port_base + port_idx
    internal_port = s['port'].split('(')[0].strip() if s['port'] else '8080'
    try:
        int(internal_port)
    except:
        internal_port = '8080'

    print(f"  # {s['name']} ({s['type']}) — east:{east_port}")
    print(f"  {s['name']}:")
    print(f"    ports:")
    print(f'      - "{east_port}:{internal_port}"')
    print("")
    port_idx += increment

# Secondary region (stateless + stateful only)
print("  # ── Secondary Region (us-west-2) ──")
print("")
for s in services:
    if s['type'] in ('stateless', 'stateful'):
        west_port = port_base + west_port_idx
        internal_port = s['port'].split('(')[0].strip() if s['port'] else '8080'
        try:
            int(internal_port)
        except:
            internal_port = '8080'

        west_name = f"{s['name']}-west"
        print(f"  # {west_name} ({s['type']}) — west:{west_port}")
        print(f"  {west_name}:")
        if s['type'] == 'stateful':
            print(f"    image: {s['image']}")
        else:
            print(f"    build:")
            print(f"      context: ./{s['name']}")
            print(f"      dockerfile: Dockerfile")
        print(f"    ports:")
        print(f'      - "{west_port}:{internal_port}"')
        print("")
        west_port_idx += increment

# Shared services just get port overrides
shared_port_idx = port_idx
print("  # ── Shared Services ──")
print("")
for s in services:
    if s['type'] in ('shared', 'infrastructure'):
        pass  # Already covered in primary region overrides

# LocalStack for Route 53
ls_port = port_base + 45
print(f"  # LocalStack (Route 53) — :{ls_port}")
print(f"  localstack:")
print(f"    image: localstack/localstack:4.4")
print(f"    ports:")
print(f'      - "{ls_port}:4566"')
print(f"    environment:")
print(f"      - SERVICES=route53")
print(f"      - DEFAULT_REGION=us-east-1")
print(f"    volumes:")
print(f"      - ./localstack/init:/etc/localstack/init/ready.d")

print("")
print("volumes:")
print("  pgdata-west:")
PYEOF

echo ""
echo "Generated: $OUTPUT"
echo ""
cat "$OUTPUT" | head -40
echo "..."
echo ""
echo "Total lines: $(wc -l < "$OUTPUT")"
